### ISSUE TITLE
I can't use css file ESP8266WebServer

### ISSUE THREAD

**Issue by sharifpt** [codemee/ESP8266WebServer#2]
Hi, 
I'm Md shariful islam .   I am a student.  Few days i am using ESP8266WebServer.py library. It’s beautiful and powerful  webserver library. It’s work faster.  Stylesheet css link can't run.   Its run when i use <style>......... </style>  but, when use this code  <link rel="stylesheet" href="styles.css">  can't load this . 

style.css and index.html in same folder. 

Please help me Sir.

**Comment by codemee** [comment]
@sharifpt could you attch your testing files so that I can try.

**Comment by sharifpt** [comment]
Thank you sir for ans me.
I will give my code in zip file on google drive. myserver.py heare my code.  Problem index.html css link not work 
`https://drive.google.com/file/d/1FDWaBE-RKuZY4fMaH3F7bw-BNUxDHlBD/view?usp=drivesdk`

**Comment by codemee** [comment]
I've commited a new version that would process relative path in the  right way.Bellow is th e screenshot of a test using files you provided.
![圖片](https://user-images.githubusercontent.com/1037913/91876420-3c1a2600-ecaf-11ea-970d-21b3d7daf83b.png)
Make sure you upload the css file and all the html files to the root of ESP32 board.

**Comment by sharifpt** [comment]
index.html file w3.css style sheet not working....
Please open index.html file and html code.  you understand this problem.....
Index.html and incss.html same code, but deferent using css style.  incss.html file loaded like your screenshot.  But index.html not loaded like this.  Thank you Sir.

**Comment by codemee** [comment]
I thinnk the problem is solved.Try the newest commit and led me know if it works?

**Comment by sharifpt** [comment]
@codemee Thanks for everything
Your new lib working good. This problem is solved .  I can now use  css and javascript file. I have one more question off topic, Can it possible this server call host name like localhost, ESP8266WebServer.com . 

Thank you again sir.

**Comment by codemee** [comment]
The question you mentioned about translating domain name to ip  address is not the business of a web server.You need to register a domain name and running a DNS server to do the work. Normally the domain name register service would provide DNS server also.You can check out some domain name register company like GoDaddy.
