### ISSUE TITLE
I want show dht11 sensor value on web page

### ISSUE THREAD

**Issue by sharifpt** [codemee/ESP8266WebServer#3]
Hello sir, 
At first thanks to you for ESP8266WebServer library module. Recently I'm trying  dht11 sensor Humidity and Temperature show html page and without refresh page update humidity and temperature value. 
How can i do this use ESP8266WebServer please help me.  
Thank you sir

**Comment by codemee** [comment]
You should go for AJAX. The feature you need isn't contolled by Web server. It's the JavaScript in the web page to request data from web server and update related text in the page in the background. Just google AJAX tutorial, you should get what you need.

**Comment by sharifpt** [comment]
If you give me some example code help me sir. Thank you sir.

**Comment by codemee** [comment]
see the [sample web page](https://github.com/codemee/ESP8266WebServer/blob/master/www/index.html)
