### ISSUE TITLE
comments in def ok(socket, code, *args)

### ISSUE THREAD

**Issue by gnrliubin** [codemee/ESP8266WebServer#4]
Line 96
```python
#     if __fileExist(msg):
#         filePath = msg
#         __sendPage(socket, filePath)
#     else:
```
Can I send  a HTML file to  ok() by uncommenting there lines?
Have you found any exceptions and comment it？

**Comment by codemee** [comment]
I guess that would work but I haven't test it. You can try it and maybe make a pull request for it.

By the way, I've rename this repository to ESPWebServer, see here

https://github.com/codemee/ESPWebServer

**Comment by gnrliubin** [comment]
got it ,thank you very much
